In [1]:
import os 
from pathlib import Path
import numpy as np
from matplotlib import pyplot as plt

from BOCS import *
from bhs import *

## Agenda... Get a feeling for the OG BOCS implementation
- understand/implement `BOCS-SA`
- then... implement 

In [2]:
n = 10
d = 26

# f
f_GT = lambda x: -0.3*x[0] + 0.2*x[1] + 0.5*x[2] - 1.5 * x[3] + 0.5 * x[4]

# X,y
X_ = np.random.binomial(p=0.5, n=1, size=n*d).reshape((n,d))
y_ = np.array([f_GT(x) for x in X_])


# Bayesian Regression
b1 = bhs(Xorg=X_, yorg=y_, nsamples=666, burnin=10, thin=1)

In [3]:
b1[0].shape # alpha collection (d, N_runs)

b1[1]         # np.mean(y)

b1[2].shape # s2 : 

b1[3].shape # t2 : 

b1[4].shape # l2

(26, 666)

## Run `BOCS` Model

In [12]:
# Paras
n = 33
d = 16

# f (groundtruth model)
f_GT = lambda x: x.sum()**2 - 2 + (x**3).sum() + 2 + (2.5*np.cos(x)**2).sum() - np.sin(x.sum())

pen = lambda x: -10*(x**2).sum()

# X,y X_vals
X_ = np.random.binomial(p=0.5, n=1, size=n*d).reshape((n,d))
y_ = np.array([f_GT(x) for x in X_])


# Bayesian Regression
b1 = bhs(Xorg=X_, yorg=y_, nsamples=666, burnin=10, thin=1)

# inputs
inputs = {'n_vars' : d, 'model' : f_GT, 'penalty' : pen, 
          'evalBudget' : 35, 'x_vals' : X_, 'y_vals' : y_}

In [13]:
model_iter, obj_iter = BOCS(inputs=inputs, order=2, acquisitionFn='SA') # SA_RUNS * ()

SA - (2.) start:   ...  kk in range(n_rand_vector)
SA - (2.) start:   ...  kk in range(n_rand_vector)
SA - (2.) start:   ...  kk in range(n_rand_vector)
SA - (2.) start:   ...  kk in range(n_rand_vector)
SA - (2.) start:   ...  kk in range(n_rand_vector)
SA - (2.) start:   ...  kk in range(n_rand_vector)
SA - (2.) start:   ...  kk in range(n_rand_vector)
SA - (2.) start:   ...  kk in range(n_rand_vector)
SA - (2.) start:   ...  kk in range(n_rand_vector)
SA - (2.) start:   ...  kk in range(n_rand_vector)


In [14]:
?BOCS

In [ ]:
plt.plot(obj_iter)
plt.show()

In [ ]:
model_iter

## Open Questions

### Geometric Rounding
- $v_{i}$s solve BQP in *expectation*?!

### $l_{p}$ penalization 
- how does `\lambda` enter the optimiation problem (in $l_{2}$)? -> see `MATLAB`

### SA
- how often are the SA samples run?

### Input transformation
- `BOCS ('18)`: `X` must be provided as $n \times p$ (already transformed) while mine requires $n \times d$ (original input feature)


In [ ]:
v_i = np.array([5.0, 3.4, 6.2, -9.4, 9.4, -5.5, 9.2, -2.2, -1.2]) / np.linalg.norm(v_i, ord=2)

In [ ]:
v_i = np.array([1, 0, -2.5, 0, 2])
# sample
N = 100000

signVec=[]
for k in range(N):
    u = np.random.normal(0,1,size=len(v_i))
    u /= np.linalg.norm(u, ord=2)
    signVec.append(np.sign(v_i @ u))
    
np.mean(signVec)

In [ ]:
u

### OG Code

In [23]:
L = np.linalg.cholesky(np.eye(d+1))

In [32]:
vecList = []
for k in range(10000):
    r = np.random.randn(d+1)   # s~ N(0,1) ... (d+1)-times
    r = r/np.linalg.norm(r)
    #y_soln = np.sign(np.dot(L.T,r))

    vecList.append(np.sign(np.dot(L.T,r)))

In [33]:
vecList

[array([-1., -1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1.,
         1., -1., -1., -1.]),
 array([-1.,  1., -1., -1.,  1., -1.,  1.,  1., -1.,  1., -1., -1.,  1.,
         1.,  1., -1.,  1.]),
 array([-1.,  1.,  1., -1., -1., -1.,  1., -1., -1.,  1.,  1., -1., -1.,
         1.,  1., -1.,  1.]),
 array([ 1.,  1., -1., -1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1.,
         1.,  1., -1., -1.]),
 array([-1.,  1., -1.,  1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,
        -1., -1., -1., -1.]),
 array([ 1.,  1., -1., -1.,  1., -1., -1., -1.,  1.,  1.,  1., -1.,  1.,
         1., -1., -1.,  1.]),
 array([-1.,  1., -1.,  1., -1., -1.,  1.,  1.,  1.,  1.,  1., -1., -1.,
        -1.,  1., -1.,  1.]),
 array([ 1., -1., -1.,  1.,  1., -1., -1.,  1., -1.,  1., -1., -1., -1.,
         1.,  1., -1., -1.]),
 array([ 1., -1., -1., -1.,  1., -1., -1., -1.,  1., -1., -1., -1., -1.,
        -1., -1., -1., -1.]),
 array([ 1.,  1.,  1., -1.,  1., -1., -1., -1.,  1.,  1.,  1., -1.,  1.,


In [ ]:
r = r/np.linalg.norm(r)
y_soln = np.sign(np.dot(L.T,r))